version: 2
jobs:
  build:
    docker:
      - image: ruby:2.6
        environment:
          - LANG: C.UTF-8

    steps:
      - checkout
      - restore_cache:
          key: dependency-{{ checksum "Gemfile.lock" }}
      - run:
          command: gem install bundler && bundle install --path vendor/bundle
      - save_cache:
          key: dependency-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: |
            cat feeds.toml | bundle exec ruby ./crawl.rb | bundle exec ruby ./generate.rb > /dev/null
